better error handling in bin scripts

diff --git a/bin/ring-check-bundle b/bin/ring-check-bundle
--- a/bin/ring-check-bundle
+++ b/bin/ring-check-bundle
@@ -1,13 +1,16 @@
 #!/bin/bash
 set -e
 BUILDER_PATH=$1
-if ! [ -d $BUILDER_PATH ]; then
+if [ -z $BUILDER_PATH ]; then
     echo "USAGE: ring-check-bundle <builder_path> [bundle_name]"
+    exit 1
+fi
+if ! [ -d $BUILDER_PATH ]; then
+    echo "ERROR: $BUILDER_PATH is not a directory!"
     exit 1
 fi
 BUNDLE_PATH=$(pwd)/${2:-"rings"}.bundle
 cd $BUILDER_PATH
-touch $BUILDER_PATH
 export COPYFILE_DISABLE=1
 find . -name \*.builder ! -wholename \*/backups/\* -print0 | \
     tar czvf $BUNDLE_PATH --null -T -
diff --git a/bin/ring-check-extract b/bin/ring-check-extract
--- a/bin/ring-check-extract
+++ b/bin/ring-check-extract
@@ -1,7 +1,11 @@
 #!/bin/bash
 BUNDLE_FILE=${1}
-if ! [ -e $BUNDLE_FILE ]; then
+if [ -z $BUNDLE_FILE ]; then
     echo "USAGE: ring-check-extract <bundle_file> [bundle_name]"
+    exit 1
+fi
+if ! [ -e $BUNDLE_FILE ]; then
+    echo "ERROR: $BUNDLE_FILE does not exist!"
     exit 1
 fi
 BUNDLE_NAME=${2:-${BUNDLE_FILE%.*}}
